routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/tour/data','TourController@getAllData')->name('tour.data');
Route::get('/tour/{id}/itenerary','TourController@getItenerary')->name('tour.itenerary');
Route::post('/tour/{id}/itenerary','TourController@storeItenerary')->name('tour.itenerary.store');
Route::get('/tour/{id}/include','TourController@getInclude')->name('tour.include');
Route::post('/tour/{id}/include','TourController@storeInclude')->name('tour.include.store');
Route::get('/tour/{id}/image','TourController@getImages')->name('tour.image');
Route::post('/tour/{id}/image','TourController@storeImage')->name('tour.image.store');

Route::resource('/tour','TourController');

Route::get('/clothing/data','ClothingController@getAllData')->name('kaos.data');
Route::get('/clothing/{id}/image','ClothingController@getImages')->name('kaos.image');
Route::post('/clothing/{id}/image','ClothingController@storeImage')->name('kaos.image.store');
Route::resource('/clothing','ClothingController');

Route::post('/gallery/{id}/image','GalleryController@storeImage')->name('gallery.image.store');
Route::resource('/gallery','GalleryController');

Route::get('booking/pending','BookingController@pending')->name('booking.pending');
Route::get('/booking/pending.json','BookingController@getPendingData')->name('booking.pending.data');
Route::get('/booking/data.json','BookingController@getAllData')->name('booking.data');
Route::resource('/booking','BookingController');


Route::post('bkonfirm/{id_booking}/{konfirmasi}/booking','BookingKonfirmasiController@konfirmasi')->name('bkonfirm.konfirmasi');
Route::get('/bkonfirm/data.json','BookingKonfirmasiController@getTableData')->name('bkonfirm.data');
Route::resource('/bkonfirm','BookingKonfirmasiController');

Route::get('/order/pending','OrderController@pending')->name('order.pending');
Route::get('/order/konfirmasi','OrderController@konfirmasi')->name('order.konfirmasi');
Route::get('/order/konfirmasi.json','OrderController@getKonfirmasiData')->name('order.konfirmasi.data');
Route::get('/order/pending.json','OrderController@getPendingData')->name('order.pending.data');
Route::get('/order/data.json','OrderController@getAllData')->name('order.data');
Route::post('/order/{id_order}/{konfirmasi}/order','OrderController@postKonfirmasi')->name('order.post.konfirmasi');
Route::resource('/order','OrderController');

Route::get('/email',function (){
    $when = Carbon\Carbon::now()->addSeconds(15);
    Mail::to("aisatriani03@gmail.com")->send(new \App\Mail\RegisterEmail());
    return 'test';
});

resources/views/partials/header.blade.php
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
    <!-- navbar-header -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ route('home') }}">
           <span>ATUPATO WEBAPPS</span>
        </a>
    </div>


</nav>

resources/views/partials/sidebar.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <!-- sidebar-collapse -->
    <div class="sidebar-collapse">
        <!-- side-menu -->
        <ul class="nav" id="side-menu">
            <li>
                <!-- user image section-->
                <div class="user-section">

                </div>
                <!--end user image section-->
            </li>

            <li class="{{ (Route::currentRouteName() == 'home') ? 'active selected' : '' }}">
                <a href="{{ route('home') }}"><i class="fa fa-dashboard fa-fw"></i>Dashboard</a>
            </li>

            <li class="{{ (Route::currentRouteName() === 'tour.index') ? 'selected' : '' }}" >
                <a href="{{route('tour.index')}}"><i class="fa fa-flask fa-fw"></i>Tour</a>
            </li>
            <li class="{{ (Route::currentRouteName() === 'clothing.index') ? 'selected' : '' }}">
                <a href="{{ route('clothing.index') }}"><i class="fa fa-table fa-fw"></i>Cloting</a>
            </li>
            <li class="{{ (Route::currentRouteName() === 'gallery.index') ? 'selected' : '' }}">
                <a href="{{ route('gallery.index') }}"><i class="fa fa-table fa-fw"></i>Gallery</a>
            </li>


            <li>
                <a href="#"><i class="fa fa-adjust"></i> Booking<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ (Route::currentRouteName() === 'booking.pending') ? 'selected' : '' }}">
                        <a href="{{ route('booking.pending') }}"><i class="fa fa-table fa-fw"></i>Pending Booking</a>
                    </li>

                    <li class="{{ (Route::currentRouteName() === 'bkonfirm.index') ? 'selected' : '' }}">
                        <a href="{{ route('bkonfirm.index') }}"><i class="fa fa-table fa-fw"></i>Konfirmasi Booking</a>
                    </li>

                    <li class="{{ (Route::currentRouteName() === 'booking.index') ? 'selected' : '' }}">
                        <a href="{{ route('booking.index') }}"><i class="fa fa-table fa-fw"></i>Booking Fix</a>
                    </li>
                </ul>
            </li>


            <li>
                <a href="#"><i class="fa fa-adjust"></i> Order<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ (Route::currentRouteName() === 'order.pending') ? 'selected' : '' }}">
                        <a href="{{ route('order.pending') }}"><i class="fa fa-table fa-fw"></i>Pending Order</a>
                    </li>

                    <li class="{{ (Route::currentRouteName() === 'order.konfirmasi') ? 'selected' : '' }}">
                        <a href="{{ route('order.konfirmasi') }}"><i class="fa fa-table fa-fw"></i>Konfirmasi Order</a>
                    </li>

                    <li class="{{ (Route::currentRouteName() === 'booking.index') ? 'selected' : '' }}">
                        <a href="{{ route('order.index') }}"><i class="fa fa-table fa-fw"></i>Order Fix</a>
                    </li>
                </ul>
            </li>


        </ul>
        <!-- end side-menu -->
    </div>
    <!-- end sidebar-collapse -->
</nav>