routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/tour/data','TourController@getAllData')->name('tour.data');
Route::get('/tour/{id}/itenerary','TourController@getItenerary')->name('tour.itenerary');
Route::post('/tour/{id}/itenerary','TourController@storeItenerary')->name('tour.itenerary.store');
Route::get('/tour/{id}/include','TourController@getInclude')->name('tour.include');
Route::post('/tour/{id}/include','TourController@storeInclude')->name('tour.include.store');
Route::get('/tour/{id}/image','TourController@getImages')->name('tour.image');
Route::post('/tour/{id}/image','TourController@storeImage')->name('tour.image.store');

Route::resource('/tour','TourController');

Route::get('/clothing/data','ClothingController@getAllData')->name('kaos.data');
Route::get('/clothing/{id}/image','ClothingController@getImages')->name('kaos.image');
Route::post('/clothing/{id}/image','ClothingController@storeImage')->name('kaos.image.store');
Route::resource('/clothing','ClothingController');

Route::post('/gallery/{id}/image','GalleryController@storeImage')->name('gallery.image.store');
Route::resource('/gallery','GalleryController');

Route::get('booking/pending','BookingController@pending')->name('booking.pending');
Route::get('/booking/pending.json','BookingController@getPendingData')->name('booking.pending.data');
Route::get('/booking/data.json','BookingController@getAllData')->name('booking.data');
Route::resource('/booking','BookingController');


Route::post('bkonfirm/{id_booking}/{konfirmasi}/booking','BookingKonfirmasiController@konfirmasi')->name('bkonfirm.konfirmasi');
Route::get('/bkonfirm/data.json','BookingKonfirmasiController@getTableData')->name('bkonfirm.data');
Route::resource('/bkonfirm','BookingKonfirmasiController');

Route::get('/order/pending','OrderController@pending')->name('order.pending');
Route::get('/order/konfirmasi','OrderController@konfirmasi')->name('order.konfirmasi');
Route::get('/order/konfirmasi.json','OrderController@getKonfirmasiData')->name('order.konfirmasi.data');
Route::get('/order/pending.json','OrderController@getPendingData')->name('order.pending.data');
Route::get('/order/data.json','OrderController@getAllData')->name('order.data');
Route::post('/order/{id_order}/{konfirmasi}/order','OrderController@postKonfirmasi')->name('order.post.konfirmasi');
Route::resource('/order','OrderController');

Route::get('/email',function (){
    $when = Carbon\Carbon::now()->addSeconds(15);
    Mail::to("aisatriani03@gmail.com")->send(new \App\Mail\RegisterEmail());
    return 'test';
});

app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    protected $table = 'bookings';
    protected $fillable = [
        'tour_id',
        'tgl_booking',
        'adult',
        'metode_pembayaran_id',
        'user_id',
        'konfirmasi',
        'status_pembayaran'
    ];

    public function tour()
    {
        return $this->belongsTo(Tour::class,'tour_id');
    }

    public function metodePembayaran()
    {
        return $this->belongsTo(MetodePembayaran::class,'metode_pembayaran_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getTotalBayarAttribute($val){
        $bayar = $this->adult * $this->tour->harga;
        return 'Rp ' .number_format($bayar, 0, ',','.');
    }
}

resources/views/bkonfirm/index.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Tour</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>Daftar Booking tour atupato</h4>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <table class="table table-striped table-bordered table-hover" id="dataTables">
                                    <thead>
                                    <tr>
                                        <th>NO</th>
                                        <th>Nama Pengirim</th>
                                        <th class="col-sm-4">Paket Tour</th>
                                        <th>Tgl Booking</th>
                                        <th>Adult</th>
                                        <th>Jumlah Bayar</th>
                                        <th>Opsi</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection

@push('css')
<link href="{{asset('siminta')}}/assets/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
@endpush

@push('js')
<script src="{{asset('siminta')}}/assets/plugins/dataTables/jquery.dataTables.js"></script>
<script src="{{asset('siminta')}}/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTables').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('bkonfirm.data') !!}',
            columns: [
                { data: 'id', name: 'id' },
                { data: 'nama_pengirim', name: 'nama_pengirim' },
                { data: 'booking.tour.nama_tour', name: 'booking.tour.nama_tour' },
                { data: 'booking.tgl_booking', name: 'booking.tgl_booking' },
                { data: 'booking.adult', name: 'booking.adult' },
                { data: 'bayar', name: 'bayar' },
                { data: 'action', name: 'action', "orderable": false, "searchable": false }
            ]
        });
    });
</script>


@endpush

resources/views/bkonfirm/view.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Konfirmasi Booking</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>{{ $bkonfirm->booking->tour->nama_tour }}</h4>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">

                                <table class="table table-hover">

                                	<tbody>
                                    <tr>
                                        <td width="200px">Nama tour</td>
                                        <td><strong>{{$bkonfirm->booking->tour->nama_tour}}</strong></td>
                                    </tr>
                                    <tr>
                                        <td>Tgl booking</td>
                                        <td>{{$bkonfirm->booking->tgl_booking}}</td>
                                    </tr>

                                    <tr>
                                        <td>Adult</td>
                                        <td>{{$bkonfirm->booking->adult}}</td>
                                    </tr>
                                    <tr>
                                        <td>Total Bayar</td>
                                        <td>{{$bkonfirm->booking->total_bayar}}</td>
                                    </tr>
                                    <tr>
                                        <td>Via</td>
                                        <td>{{$bkonfirm->booking->metodePembayaran->nama_metode}}</td>
                                    </tr>
                                    <tr>
                                        <td>Nama Pengirim</td>
                                        <td>{{$bkonfirm->nama_pengirim}}</td>
                                    </tr>

                                    <tr>
                                        <td>Bukti pembayaran</td>
                                        <td><img width="300px" height="300px" src="{{$bkonfirm->gambar}}"></td>
                                    </tr>

                                	</tbody>
                                </table>


                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection