routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/tour/data','TourController@getAllData')->name('tour.data');
Route::get('/tour/{id}/itenerary','TourController@getItenerary')->name('tour.itenerary');
Route::post('/tour/{id}/itenerary','TourController@storeItenerary')->name('tour.itenerary.store');
Route::get('/tour/{id}/include','TourController@getInclude')->name('tour.include');
Route::post('/tour/{id}/include','TourController@storeInclude')->name('tour.include.store');
Route::get('/tour/{id}/image','TourController@getImages')->name('tour.image');
Route::post('/tour/{id}/image','TourController@storeImage')->name('tour.image.store');

Route::resource('/tour','TourController');

Route::get('/clothing/data','ClothingController@getAllData')->name('kaos.data');
Route::get('/clothing/{id}/image','ClothingController@getImages')->name('kaos.image');
Route::post('/clothing/{id}/image','ClothingController@storeImage')->name('kaos.image.store');
Route::resource('/clothing','ClothingController');

Route::post('/gallery/{id}/image','GalleryController@storeImage')->name('gallery.image.store');
Route::resource('/gallery','GalleryController');

Route::get('booking/pending','BookingController@pending')->name('booking.pending');
Route::get('/booking/pending.json','BookingController@getPendingData')->name('booking.pending.data');
Route::get('/booking/data.json','BookingController@getAllData')->name('booking.data');
Route::resource('/booking','BookingController');


Route::post('bkonfirm/{id_booking}/{konfirmasi}/booking','BookingKonfirmasiController@konfirmasi')->name('bkonfirm.konfirmasi');
Route::get('/bkonfirm/data.json','BookingKonfirmasiController@getTableData')->name('bkonfirm.data');
Route::resource('/bkonfirm','BookingKonfirmasiController');

Route::get('/order/pending','OrderController@pending')->name('order.pending');
Route::get('/order/konfirmasi','OrderController@konfirmasi')->name('order.konfirmasi');
Route::get('/order/konfirmasi.json','OrderController@getKonfirmasiData')->name('order.konfirmasi.data');
Route::get('/order/pending.json','OrderController@getPendingData')->name('order.pending.data');
Route::get('/order/data.json','OrderController@getAllData')->name('order.data');
Route::post('/order/{id_order}/{konfirmasi}/order','OrderController@postKonfirmasi')->name('order.post.konfirmasi');
Route::resource('/order','OrderController');

Route::get('/email',function (){
    $when = Carbon\Carbon::now()->addSeconds(15);
    Mail::to("aisatriani03@gmail.com")->send(new \App\Mail\RegisterEmail());
    return 'test';
});

app/Tour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class Tour extends Model
{

    protected $table = 'tours';
    protected $fillable = [
        'nama_tour',
        'deskripsi',
        'telp',
        'latitude',
        'longitude',
        'itenerary',
        'includes',
        'harga'
    ];

    public $hidden = ['media','images'];

    public function images()
    {
        return $this->morphMany(Images::class,'model');
    }

    public function getIteneraryAttribute($val)
    {
        return json_decode($val);
    }

    public function getIncludesAttribute($val)
    {
        return json_decode($val);
    }
    public function getHargaFormatAttribute($val)
    {
        return 'Rp '. number_format($this->harga,0,',','.') . '/pax';
    }
}

app/Http/Controllers/TourController.php
<?php

namespace App\Http\Controllers;

use App\Images;
use App\Tour;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;

class TourController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('tour.index');
    }

    public function getAllData()
    {

        $tour = Tour::all();
        return Datatables::of($tour)
            ->addColumn('nama',function ($tour){
                return '<a href="'.route('tour.show',[$tour->id]).'">'.$tour->nama_tour.'</a>';
            })
            ->addColumn('harga_format',function ($tour){
                return 'Rp '. number_format($tour->harga,0,',','.') .'/pax';
            })
            ->addColumn('action',function ($tour){
                return '
                <a class="btn btn-sm btn-warning" href="'.route('tour.itenerary',['id'=>$tour->id]).'" ><i class="fa fa-list"></i> Itenerary</a>
                <a class="btn btn-sm btn-warning" href="'.route('tour.include',['id'=>$tour->id]).'" ><i class="fa fa-list-alt"></i> Include</a>
                <a class="btn btn-sm btn-info" href="'.route('tour.image',['id'=>$tour->id]).'" ><i class="fa fa-picture-o"></i> Gambar</a>
                <a class="btn btn-sm btn-primary" href="'.route('tour.edit',['id'=>$tour->id]).'" ><i class="fa fa-pencil-square-o"></i> Edit</a>
                 <a data-confirm="Yakin ingin menghapus data ini?" data-method="delete" class="btn btn-sm btn-danger" href="'.route('tour.destroy',[$tour->id]).'" ><i class="fa fa-times"></i> Hapus</a>';
            })
            ->make(true);
    }

    public function getAllTour()
    {
        $tour = Tour::all();
        for ($i = 0 ; $i < count($tour); $i++){
            $media = $tour[$i]->images;
            $arr_media = [];
            //for ($j = 0; $j < count($media); $j++){
            foreach($media as $m){
                $arr_media[] = $m->img_url;
            }

            $tour[$i]->image = $arr_media;
            $tour[$i]->harga_text = $tour[$i]->harga_format;
            $tour[$i]->min_text = 'min '. $tour[$i]->min_require .' org';
        }

        return $tour;
    }

    public function getItenerary($id)
    {
        $tour = Tour::findOrFail($id);
        return view('tour.form-itenerary',compact('tour'));
    }

    public function storeItenerary(Request $request, $id)
    {
        //dd($request->all());
        $input = $request->all();
        $arr_itenerary = $input['itenerary'];
        $str_itenerary = json_encode($arr_itenerary);

        $tour = Tour::findOrFail($id);
        $tour->itenerary = $str_itenerary;
        $tour->save();

        return redirect()->back();
    }

    public function getInclude($id)
    {
        $tour = Tour::findOrFail($id);
        return view('tour.form-include',compact('tour'));
    }

    public function storeInclude(Request $request, $id)
    {
        //dd($request->all());
        $input = $request->all();
        $arr_includes = $input['include'];
        $str_includes = json_encode($arr_includes);

        $tour = Tour::findOrFail($id);
        $tour->includes = $str_includes;
        $tour->save();

        return redirect()->back();
    }

    public function getImages($id)
    {
        $tour = Tour::findOrFail($id);
        //$media = $tour->getMedia($tour->nama_tour);
        $media = $tour->images;
       // return $media[0]->getUrl()
        return view('tour.image',compact('tour','media'));
    }

    public function storeImage(Request $request, $id)
    {


        //dd(Input::file('gambar'));
        $tour = Tour::findOrFail($id);
        $image =  $request->file('gambar');
        //$tour->addMedia($image)->toCollection($tour->nama_tour);

        $ext = $image->getClientOriginalExtension();
        $fname = str_random(16);

        $image->move(public_path('media'),$fname.'.'.$ext);

        $im = new Images();
        $im->img_url = '/media' .'/'. $fname.'.'.$ext;
        $im->img_name = $fname.'.'.$ext;

        $tour->images()->save($im);


        return redirect()->back();
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tour.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $input = $request->all();
        $this->validate($request,[
            'nama_tour'=>'required',
            'deskripsi'=>'required',
            'latitude'=>'required',
            'longitude'=>'required',
            'harga'=>'required',
        ]);

        Tour::create($input);
        return redirect(route('tour.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tour = Tour::findOrFail($id);
        $itenerary = $tour->itenerary;
        return view('tour.show',compact('tour','itenerary'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tour = Tour::findOrFail($id);
        return view('tour.edit',compact('tour'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request->all());
        $input = $request->all();
        $this->validate($request,[
            'nama_tour'=>'required',
            'deskripsi'=>'required',
            'latitude'=>'required',
            'longitude'=>'required',
            'harga'=>'required',
        ]);

        $tour = Tour::findOrFail($id);
        $tour->fill($input)->save();

        return redirect(route('tour.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tour = Tour::findOrFail($id);
        $tour->delete();

        return redirect(route('tour.index'));
    }
}

resources/views/tour/edit.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Tour</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>Edit Data Tour Atupato</h4>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-8">

                                <form action="{{route('tour.update',[$tour->id])}}" method="post" class="form-horizontal" role="form">
                                    {{ method_field('PUT') }}
                                    {{ csrf_field() }}

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="nama_tour" class="col-sm-2 control-label">Nama tour</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="nama_tour" class="form-control" id="nama_tour" placeholder="Nama Tour" value="{{ $tour->nama_tour }}">
                                            @if(count($errors) > 0)
                                            <span class="help-block">{{ $errors->first('nama_tour') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="deskripsi" class="col-sm-2 control-label">Deskripsi</label>
                                        <div class="col-sm-10">
                                            <textarea name="deskripsi" style="height: 150px" class="form-control" id="deskripsi" placeholder="Deskripsi">{{ $tour->deskripsi }}</textarea>
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('deskripsi') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="telp" class="col-sm-2 control-label">Telp</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="telp" class="form-control" id="telp" placeholder="Telp" value="{{ $tour->telp }}">
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}} ">
                                        <label for="latitude" class="col-sm-2 control-label">Latitude</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="latitude" class="form-control" id="latitude" value="{{ $tour->latitude }}"
                                                   placeholder="Latitude">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('latitude') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="longitude" class="col-sm-2 control-label">Longitude</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="longitude" class="form-control" id="longitude" value="{{ $tour->longitude }}"
                                                   placeholder="Longitude">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('longitude') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="harga" class="col-sm-2 control-label">Harga</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="harga" class="form-control" id="harga" placeholder="Harga" value="{{ $tour->harga }}">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('harga') }}</span>
                                            @endif
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-sm-10 col-sm-offset-2">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection

resources/views/tour/form.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Tour</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>Tour Atupato</h4>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-8">

                                <form action="{{route('tour.store')}}" method="post" class="form-horizontal" role="form">

                                    {{ csrf_field() }}

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="nama_tour" class="col-sm-2 control-label">Nama tour</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="nama_tour" class="form-control" id="nama_tour" placeholder="Nama Tour">
                                            @if(count($errors) > 0)
                                            <span class="help-block">{{ $errors->first('nama_tour') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="deskripsi" class="col-sm-2 control-label">Deskripsi</label>
                                        <div class="col-sm-10">
                                            <textarea name="deskripsi" style="height: 150px" class="form-control" id="deskripsi" placeholder="Deskripsi"></textarea>
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('deskripsi') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="telp" class="col-sm-2 control-label">Telp</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="telp" class="form-control" id="telp" placeholder="Telp">
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="latitude" class="col-sm-2 control-label">Latitude</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="latitude" class="form-control" id="latitude"
                                                   placeholder="Latitude">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('latitude') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="longitude" class="col-sm-2 control-label">Longitude</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="longitude" class="form-control" id="longitude"
                                                   placeholder="Longitude">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('longitude') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="harga" class="col-sm-2 control-label">Harga</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="harga" class="form-control" id="harga" placeholder="Harga">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('harga') }}</span>
                                            @endif
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-sm-10 col-sm-offset-2">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection

resources/views/tour/image.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Tour</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>Daftar Gambar Paket {{ $tour->nama_tour }}</h4>
                        </div>
                        {{--<div class="pull-right">--}}
                            {{--<a class="btn btn-primary" href="{{ route('tour.create') }}">Tambahkan</a>--}}
                        {{--</div>--}}
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                           <div class="col-lg-8">
                               @foreach($media as $m)
                           	    <img style="margin-bottom: 10px" src="{{ $m->img_url }}" height="200px" width="200px"/>
                               @endforeach
                           </div>
                            <div class="col-lg-4">
                            	<div class="panel panel-info">
                            		  <div class="panel-heading">
                            				<h3 class="panel-title">Upload Gambar</h3>
                            		  </div>
                            		  <div class="panel-body">
                            				<form action="{{ route('tour.image.store',[$tour->id]) }}" enctype="multipart/form-data" method="post" role="form">

                            					<div class="form-group">
                            						<label for=""></label>
                            						<input type="file" class="form-control" name="gambar" id="gambar" placeholder="Input...">

                            					</div>
                            				

                            					<button type="submit" class="btn btn-primary">Upload</button>
                            				</form>
                            		  </div>
                            	</div>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection

@push('css')

@endpush

@push('js')

<script>
    $(document).ready(function () {

    });
</script>


@endpush

resources/views/tour/index.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Tour</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>Daftar Paket tour atupato</h4>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('tour.create') }}">Tambahkan</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <table class="table table-striped table-bordered table-hover" id="dataTables">
                                    <thead>
                                    <tr>
                                        <th>NO</th>
                                        <th class="col-sm-4">Paket Tour</th>
                                        <th>Harga</th>
                                        <th>Opsi</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection

@push('css')
<link href="{{asset('siminta')}}/assets/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
@endpush

@push('js')
<script src="{{asset('siminta')}}/assets/plugins/dataTables/jquery.dataTables.js"></script>
<script src="{{asset('siminta')}}/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTables').DataTable({
            processing: true,
            serverSide: true,
            filter: false,
            ajax: '{!! route('tour.data') !!}',
            columns: [
                { data: 'id', name: 'id' },
                { data: 'nama', name: 'nama' },
                { data: 'harga_format', name: 'harga_format' },
                { data: 'action', name: 'action' }
            ]
        });
    });
</script>


@endpush