routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/tour/data','TourController@getAllData')->name('tour.data');
Route::get('/tour/{id}/itenerary','TourController@getItenerary')->name('tour.itenerary');
Route::post('/tour/{id}/itenerary','TourController@storeItenerary')->name('tour.itenerary.store');
Route::get('/tour/{id}/include','TourController@getInclude')->name('tour.include');
Route::post('/tour/{id}/include','TourController@storeInclude')->name('tour.include.store');
Route::get('/tour/{id}/image','TourController@getImages')->name('tour.image');
Route::post('/tour/{id}/image','TourController@storeImage')->name('tour.image.store');

Route::resource('/tour','TourController');

Route::get('/clothing/data','ClothingController@getAllData')->name('kaos.data');
Route::get('/clothing/{id}/image','ClothingController@getImages')->name('kaos.image');
Route::post('/clothing/{id}/image','ClothingController@storeImage')->name('kaos.image.store');
Route::resource('/clothing','ClothingController');

Route::post('/gallery/{id}/image','GalleryController@storeImage')->name('gallery.image.store');
Route::resource('/gallery','GalleryController');

Route::get('booking/pending','BookingController@pending')->name('booking.pending');
Route::get('/booking/pending.json','BookingController@getPendingData')->name('booking.pending.data');
Route::get('/booking/data.json','BookingController@getAllData')->name('booking.data');
Route::resource('/booking','BookingController');


Route::post('bkonfirm/{id_booking}/{konfirmasi}/booking','BookingKonfirmasiController@konfirmasi')->name('bkonfirm.konfirmasi');
Route::get('/bkonfirm/data.json','BookingKonfirmasiController@getTableData')->name('bkonfirm.data');
Route::resource('/bkonfirm','BookingKonfirmasiController');

Route::get('/order/pending','OrderController@pending')->name('order.pending');
Route::get('/order/konfirmasi','OrderController@konfirmasi')->name('order.konfirmasi');
Route::get('/order/konfirmasi.json','OrderController@getKonfirmasiData')->name('order.konfirmasi.data');
Route::get('/order/pending.json','OrderController@getPendingData')->name('order.pending.data');
Route::get('/order/data.json','OrderController@getAllData')->name('order.data');
Route::post('/order/{id_order}/{konfirmasi}/order','OrderController@postKonfirmasi')->name('order.post.konfirmasi');
Route::resource('/order','OrderController');

Route::get('/email',function (){
    $when = Carbon\Carbon::now()->addSeconds(15);
    Mail::to("aisatriani03@gmail.com")->send(new \App\Mail\RegisterEmail());
    return 'test';
});

app/Http/Controllers/ClothingController.php
<?php

namespace App\Http\Controllers;

use App\Images;
use App\Kaos;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;
use Yajra\Datatables\Datatables;

class ClothingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kaos = Kaos::all();
        return view('clothing.index',compact('kaos'));
    }

    public function getAllData()
    {
        $kaos = Kaos::all();
        return Datatables::of($kaos)
            ->addColumn('action',function ($kaos){
                return '
                <a class="btn btn-sm btn-primary" href="'.route('clothing.show',['id'=>$kaos->id]).'" ><i class="fa fa-list-alt"></i> Detail</a>
                <a class="btn btn-sm btn-primary" href="'.route('kaos.image',['id'=>$kaos->id]).'" ><i class="fa fa-picture-o"></i> Gambar</a>
               <a class="btn btn-sm btn-primary" href="'.route('clothing.edit',['id'=>$kaos->id]).'" ><i class="fa fa-pencil-square-o"></i> Edit</a>
                 <a data-confirm="Yakin ingin menghapus data ini?" data-method="delete" class="btn btn-sm btn-danger" href="'.route('clothing.destroy',[$kaos->id]).'" ><i class="fa fa-times"></i> Hapus</a>';
            })
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clothing.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $this->validate($request, [
            'nama_kaos' => 'required',
            'ukuran' => 'required',
            'bahan' => 'required',
            'sablon' => 'required',
            'warna' => 'required',
            'harga' => 'required',
            'stok' => 'required',
            'gambar' => 'required'
        ]);

        $input = $request->all();
        $gambar = $request->file('gambar');

        DB::transaction(function () use ($gambar,$input) {

            $kaos = Kaos::create($input);

            //$kaosMedia = Kaos::findOrFail($kaos->id);

            $kaos->addMedia($gambar)->toCollection($kaos->nama_kaos);

        });



        return redirect()->back()->with(['success'=> 'Data Berhasil ditambahkan']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kaos = Kaos::findOrFail($id);
        return view('clothing.view',compact('kaos'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kaos = Kaos::findOrFail($id);
        return view('clothing.edit',compact('kaos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $kaos = Kaos::findOrFail($id);
        $kaos->fill($input)->save();

        return redirect(route('clothing.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kaos = Kaos::findOrFail($id);
        $kaos->delete();

        return redirect()->back();

    }

    public function getImages($id)
    {
        $kaos = Kaos::findOrFail($id);
        //$media = $kaos->getMedia($kaos->nama_kaos);
        $media = $kaos->images;

        return view('clothing.image',compact('kaos','media'));
    }

    public function storeImage(Request $request, $id)
    {


        //dd(Input::file('gambar'));
        $kaos = Kaos::findOrFail($id);
        $image =  $request->file('gambar');
        //$kaos->addMedia($image)->toCollection($kaos->nama_kaos);
        $ext = $image->getClientOriginalExtension();
        $fname = str_random(16);

        $image->move(public_path('media'),$fname.'.'.$ext);

        $im = new Images();
        $im->img_url = '/media' .'/'. $fname.'.'.$ext;
        $im->img_name = $fname.'.'.$ext;

        $kaos->images()->save($im);

        return redirect()->back();
    }

    //===================== API

    public function getAllKaos()
    {
        $kaos = Kaos::all();
        for ($i = 0 ; $i < count($kaos); $i++){
            $media = $kaos[$i]->images;
            $arr_media = [];
            for ($j = 0; $j < count($media); $j++){
                $arr_media[] = $media[$j]->img_url;
            }
            $kaos[$i]->image = $arr_media;
            $kaos[$i]->harga_text = $kaos[$i]->harga_format;
        }
        return $kaos;
    }
}

resources/views/clothing/edit.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Tour</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>Tour Atupato</h4>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">

                                @if (count($errors) > 0)
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif


                                <form action="{{route('clothing.update',[$kaos->id])}}" method="post" enctype="multipart/form-data" class="form-horizontal" role="form">
                                    {{ csrf_field() }}
                                    {{ method_field('PUT') }}

                                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="nama_tour" class="col-sm-2 control-label">Nama Kaos</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="nama_kaos" class="form-control" id="nama_kaos" placeholder="Nama Kaos" value="{{$kaos->nama_kaos}}">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('nama_kaos') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="deskripsi" class="col-sm-2 control-label">Ukuran</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="ukuran" class="form-control" id="ukuran" placeholder="Ukuran" value="{{$kaos->ukuran}}" >
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('ukuran') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="deskripsi" class="col-sm-2 control-label">Bahan</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="bahan" class="form-control" id="bahan" placeholder="Bahan" value="{{$kaos->bahan}}">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('bahan') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="deskripsi" class="col-sm-2 control-label">Sablon</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="sablon" class="form-control" id="sablon" placeholder="Sablom" value="{{$kaos->sablon}}" >
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('bahan') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="latitude" class="col-sm-2 control-label">Warna</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="warna" class="form-control" id="warna"
                                                   placeholder="Warna" value="{{$kaos->warna}}">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('warna') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="longitude" class="col-sm-2 control-label">Harga</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="harga" class="form-control" id="harga"
                                                   placeholder="Harga" value="{{$kaos->harga}}">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('harga') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="harga" class="col-sm-2 control-label">Stok</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="stok" class="form-control" id="stok" placeholder="Stok" value="{{$kaos->stok}}" >
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('stok') }}</span>
                                            @endif
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-sm-10 col-sm-offset-2">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>

                                </div>

                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">Gambar Baju</h3>
                                        </div>
                                        <div class="panel-body form-inline">
                                                <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                                    <label for=""></label>
                                                    <input type="file" class="form-control" name="gambar" id="gambar" placeholder="Input...">
                                                    @if(count($errors) > 0)
                                                        <span class="help-block">{{ $errors->first('gambar') }}</span>
                                                    @endif
                                                </div>
                                        </div>
                                    </div>
                                </div>






                                </form>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection

resources/views/clothing/form.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Tour</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>Tour Atupato</h4>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">

                                @if (count($errors) > 0)
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif


                                <form action="{{route('clothing.store')}}" method="post" enctype="multipart/form-data" class="form-horizontal" role="form">
                                    {{ csrf_field() }}

                                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="nama_tour" class="col-sm-2 control-label">Nama Kaos</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="nama_kaos" class="form-control" id="nama_kaos" placeholder="Nama Kaos">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('nama_kaos') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="deskripsi" class="col-sm-2 control-label">Ukuran</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="ukuran" class="form-control" id="ukuran" placeholder="Ukuran">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('ukuran') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="deskripsi" class="col-sm-2 control-label">Bahan</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="bahan" class="form-control" id="bahan" placeholder="Bahan">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('bahan') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="deskripsi" class="col-sm-2 control-label">Sablon</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="sablon" class="form-control" id="sablon" placeholder="Sablom">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('bahan') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="latitude" class="col-sm-2 control-label">Warna</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="warna" class="form-control" id="warna"
                                                   placeholder="Warna">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('warna') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="longitude" class="col-sm-2 control-label">Harga</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="harga" class="form-control" id="harga"
                                                   placeholder="Harga">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('harga') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                        <label for="harga" class="col-sm-2 control-label">Stok</label>
                                        <div class="col-sm-10">
                                            <input type="text" name="stok" class="form-control" id="stok" placeholder="Stok">
                                            @if(count($errors) > 0)
                                                <span class="help-block">{{ $errors->first('stok') }}</span>
                                            @endif
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-sm-10 col-sm-offset-2">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>

                                </div>

                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">Gambar Baju</h3>
                                        </div>
                                        <div class="panel-body form-inline">
                                                <div class="form-group {{ (count($errors) > 0) ? 'has-error' : ''}}">
                                                    <label for=""></label>
                                                    <input type="file" class="form-control" name="gambar" id="gambar" placeholder="Input...">
                                                    @if(count($errors) > 0)
                                                        <span class="help-block">{{ $errors->first('gambar') }}</span>
                                                    @endif
                                                </div>
                                        </div>
                                    </div>
                                </div>






                                </form>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection

resources/views/clothing/image.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Clothing</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>Daftar Gambar {{ $kaos->nama_kaos }}</h4>
                        </div>
                        {{--<div class="pull-right">--}}
                            {{--<a class="btn btn-primary" href="{{ route('tour.create') }}">Tambahkan</a>--}}
                        {{--</div>--}}
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                           <div class="col-lg-8">
                               @foreach($media as $m)
                           	    <img style="margin-bottom: 10px" src="{{ $m->img_url }}" height="200px" width="200px"/>
                               @endforeach
                           </div>
                            <div class="col-lg-4">
                            	<div class="panel panel-info">
                            		  <div class="panel-heading">
                            				<h3 class="panel-title">Upload Gambar</h3>
                            		  </div>
                            		  <div class="panel-body">
                            				<form action="{{ route('kaos.image.store',[$kaos->id]) }}" enctype="multipart/form-data" method="post" role="form">

                            					<div class="form-group">
                            						<label for=""></label>
                            						<input type="file" class="form-control" name="gambar" id="gambar" placeholder="Input...">

                            					</div>
                            				

                            					<button type="submit" class="btn btn-primary">Upload</button>
                            				</form>
                            		  </div>
                            	</div>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection

@push('css')

@endpush

@push('js')

<script>
    $(document).ready(function () {

    });
</script>


@endpush

resources/views/clothing/index.blade.php
@extends('layouts')

@section('content')
    <div class="row">
        <!-- Page Header -->
        <div class="col-lg-12">
            <h1 class="page-header">Tour</h1>
        </div>
        <!--End Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Form Elements -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h4>Daftar Paket tour atupato</h4>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-primary" href="{{ route('clothing.create') }}">Tambahkan</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <table class="table table-striped table-bordered table-hover" id="dataTables">
                                    <thead>
                                    <tr>
                                        <th>NO</th>
                                        <th class="col-sm-4">Paket Tour</th>
                                        <th>Ukuran</th>
                                        <th>Harga</th>
                                        <th>Stok</th>
                                        <th>Opsi</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
@endsection

@push('css')
<link href="{{asset('siminta')}}/assets/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
@endpush

@push('js')
<script src="{{asset('siminta')}}/assets/plugins/dataTables/jquery.dataTables.js"></script>
<script src="{{asset('siminta')}}/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
<script>
    $(document).ready(function () {
        $('#dataTables').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('kaos.data') !!}',
            columns: [
                { data: 'id', name: 'id' },
                { data: 'nama_kaos', name: 'nama_kaos' },
                { data: 'ukuran', name: 'ukuran' },
                { data: 'harga', name: 'harga' },
                { data: 'stok', name: 'stok' },
                { data: 'action', name: 'action' }
            ]
        });
    });
</script>


@endpush